### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by LucaPolese** [LucaPolese/LaboratorioTechWeb#1]
- [x] Modificare le description
- [x] Controllare <a href="../index.html" xml:lang="en">Home</a>
- [x] Completare `protagonisti.html` 
- [x] Sistemare i titoli
